### ISSUE TITLE
[enhancement] Allow source/content attributes for dynamic zones (create zonefile if they not exists)

### ISSUE THREAD

**Issue by rayderua** [smoeding/puppet-bind#6]
Hello!
I tried to create dynamic _acme-challenge zone  for letsencrypt + dns, but currently it not possible create dynaimic zone with source/content.
So we need create zonefile manually ( which is inconvenient, because we want puppet to do everything for us, right? )
Or we need run puppet twice 

first run for create primary zonefile:
```yaml
bind::zones::primary:
  _acme-challenge.example.com:
    view: 'zones'
    content: |
      $ORIGIN _acme-challenge.example.com.
      $TTL 10800      ; 3 hours
      @ IN SOA ns1.example.com. webmaster.example.com (1595157292 300 60 86400 60)
      @ NS      ns1.example.com
```

and second run to enable dynamic zone:
```yaml
bind::zones::primary:
  _acme-challenge.example.com:
    view: 'zones'
    update_policy: ['grant certbot name _acme-challenge.example.com. txt']
```

I want to suggest to allow use source/content options with update_policy together, but to create a zonefile for dynamic zones only if they not exists.

For resolution just need to add an replace attribute for zonefile like this:
```puppet
file { $zonefile:
  replace      => ( !empty($update_policy) ) ? { true => false, default => true },
}
```
